# Generated by Django 4.0.2 on 2022-03-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
